[build]
  publish = "."
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[template.plugins]
  # Optional: for Netlify CLI
